# Generated by Django 3.0 on 2021-02-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210217_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
